---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: doorbanner/themes/stanne/layouts/index.html
  label: Homepage template
- type: document
  path: doorbanner/content/video/video.md
  label: Video Page
- type: directory
  path: doorbanner/themes/stanne/layouts
  label: Theme Templates
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: doorbanner/themes/stanne/assets
  label: Styles & Scripts
  create: all
  match: "**/*"
  new_doc_ext: ".scss"
- type: directory
  path: doorbanner/data
  label: Data
  create: all
  match: "*"
- type: document
  path: doorbanner/config.toml
  label: Our Config File
upload_dir: doorbanner/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.75.1
