baseURL = "http://example.org/"
languageCode = "en-us"
theme = "stanne"
title = "Baby Jesus Door Banners"
[[menu.nav]]
name = "Buy Now"
url = "https://stanneaz.org"
weight = 3
[[menu.nav]]
name = "Watch Video"
url = "video"
weight = 2
[[menu.nav]]
name = "Home"
weight = 1
[params]
author = "Baby Jesus Door Banners"
dateFormat = "26 FEB 1994"
description = "Share the joy of Christmas by bringing baby Jesus to your neighborhood. One door at a time."
[params.banner]
background_image = "images/backgrounds/hero-background.jpg"
enable = true
heading = "Baby Jesus Door Banners"
logo = "images/logo.png"
primary_button = " Buy Now  "
primary_button_url = "https://stanneaz.org"
secondary_button = " Watch Awesome Video "
secondary_button_url = "contact"
tagline = "Share the joy of Christmas by bringing baby Jesus to your neighborhood. One door at a time."
[params.footer.contactInfo]
address = "440 E Elliot Rd<br>Gilbert, AZ 85234"
email = "stanneaz.org/contact"
phone = "480-507-4400"
title = "Contact Info"
[params.footer.service]
description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
title = "We help brands:"
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Company"
url = "about"
[[params.footer.sitemap.link]]
name = "Projects"
url = "portfolio"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Medium"
url = "#"
[[params.footer.social.link]]
name = "Behance"
url = "#"
[[params.footer.social.link]]
name = "Dribbble"
url = "#"
[[params.footer.social.link]]
name = "Instagram"
url = "#"
[params.plan]
background_image = "images/backgrounds/cta-background.jpg"
enable = true
title = "THE PLAN"
